#!/bin/sh
# shell script to prepend i3status with cmus song and artist

artist=$(cmus-remote -Q | grep ' artist ' | cut -d ' ' -f3-)
song=$(cmus-remote -Q | grep title | cut -d ' ' -f3-)

if [ ! -z "$artist" ]
then
	echo "$artist - $song" || exit 1
else
	echo 'Nothing playing...' || exit 1
fi